# Generated by Django 3.2 on 2023-01-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True)),
                ('dni', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('alta', 'alta'), ('derivado', 'derivado')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='historiaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('profesional', models.CharField(blank=True, max_length=200)),
                ('paciente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.paciente')),
            ],
        ),
    ]
