# Generated by Django 3.2 on 2023-01-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20230114_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='detalle_derivacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
