# Generated by Django 3.2 on 2023-01-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_paciente_detalle_derivacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='informe',
            new_name='evolucion',
        ),
    ]
