# Generated by Django 3.2 on 2023-01-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_rename_informe_evolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='pacientes'),
        ),
    ]
