# Generated by Django 3.2 on 2023-01-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_paciente_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivacion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='derivaciones'),
        ),
        migrations.AddField(
            model_name='evolucion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='evoluciones'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='Hc'),
        ),
    ]
