# Generated by Django 3.2 on 2023-01-15 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20230114_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('cumplio', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.paciente')),
            ],
        ),
    ]
