# Generated by Django 3.2 on 2023-01-15 03:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='cumplio',
        ),
        migrations.AddField(
            model_name='turno',
            name='creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='turno',
            name='dia',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(choices=[('2 PM', '2 PM'), ('3 PM', '3 PM'), ('4 PM', '4 PM'), ('5 PM', '5 PM'), ('6 PM', '6 PM'), ('7 PM', '7 PM')], default='3 PM', max_length=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.paciente'),
        ),
    ]
