# Generated by Django 3.2 on 2023-01-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20230115_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cumplio',
            field=models.BooleanField(default=True),
        ),
    ]
