# Generated by Django 3.2 on 2023-01-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_turno_cumplio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='turno',
        ),
    ]
